__version__:
  serializer: 1
  data: 8
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 5.25261561059085
        Brightness: 1.8
        ExposureTime: 10000
        Gain: 1.04887554535105
    - Acquisition:
        Aperture: 3.52958004188344
        Brightness: 1.8
        ExposureTime: 10000
        Gain: 1.526405051205
    - Acquisition:
        Aperture: 2.76161390684138
        Brightness: 1.8
        ExposureTime: 10000
        Gain: 3.01201407639523
    - Acquisition:
        Aperture: 1.75212820027567
        Brightness: 1.8
        ExposureTime: 10000
        Gain: 4.07824827449941
  Experimental:
    Engine: phase
  Processing:
    Color:
      Balance:
        Blue: 1
        Green: 1
        Red: 1
      Experimental:
        ToneMapping:
          Enabled: hdrOnly
      Gamma: 1
    Filters:
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: no
            Strength: 0.4
          Removal:
            Enabled: no
            Threshold: 0.5
      Noise:
        Removal:
          Enabled: yes
          Threshold: 7
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 5
      Reflection:
        Removal:
          Enabled: no
      Smoothing:
        Gaussian:
          Enabled: yes
          Sigma: 1.5
